get cross contacts
duniapay/backendtools pull request #20
Opened 2021-02-24 13:22 UTC by PogudoTanya

2021-02-26 11:07 UTC, liubaterehova requested changes
add function that process phonenumbers : remove "-", "()", add "+" if necessary and remove all spaces

2021-02-26 15:43 UTC, liubaterehova commented on src/users/users.service.ts
> +      const processedListCrossContacts = rawListContacts.filter(
find

2021-02-26 16:04 UTC, liubaterehova commented on src/users/users.service.ts
> +      if (formattedPhoneNumber.includes('+')) return formattedPhoneNumber;
change it

2021-02-26 16:05 UTC, liubaterehova commented on src/users/users.service.ts
> +          return contact.phoneNumber === rawContact.phoneNumber;
process rawContact.phoneNumber

2021-03-01 09:18 UTC, liubaterehova reviewed
Please merge your commits in one commit, fix my issues

2021-03-01 09:18 UTC, liubaterehova commented on src/users/users.service.ts
> +      return formattedPhoneNumber;
just `return this.getCorrectPhone(contact.phoneNumber);`

2021-03-01 09:18 UTC, liubaterehova commented on src/users/users.service.ts
> +    return `+${phoneNumber.replace(/[^+\d]+/g, '')}`;
use ternarny operator here

2021-03-01 09:18 UTC, liubaterehova commented on src/users/users.service.ts
> +      });
without return 
```
const processedListCrossContacts = rawListContacts.find(
        (rawContact) =>
          contact.phoneNumber === this.getCorrectPhone(rawContact.phoneNumber),
      );
```

2021-03-01 09:37 UTC, apsevkin commented on src/users/users.service.ts
> +  public async findCrossContacts(
remove async

2021-03-01 09:37 UTC, apsevkin commented on src/users/users.service.ts
> +  ): Promise<FindCrossContactsDto[]> {
should return FindCrossContactsDto[] without Promise

2021-03-01 11:58 UTC, liubaterehova approved these changes

2021-03-01 11:58 UTC, merged