send sms and show not duniapay user
duniapay/backendtools pull request #21
Opened 2021-02-25 19:36 UTC by PogudoTanya

2021-03-01 15:08 UTC, apsevkin approved these changes

2021-03-01 15:08 UTC, apsevkin commented on src/users/users.service.ts
> +    const listPhonesCrossContacts = rawListCrossContacts.map(
remove it

2021-03-01 15:08 UTC, apsevkin commented on src/users/users.service.ts
> +    const listPhonesNotDuniapayContacts = rawListContactsPhone.filter(
use rawListContacts instead

2021-03-01 15:08 UTC, apsevkin commented on src/services/twilio.service.ts
> +      return await this.client.messages.create({
remove unnecessary await; add new params to function for a message body

2021-03-01 15:08 UTC, apsevkin commented on src/services/twilio.service.ts
> +      throw new HttpException(
handle http exception in the users controller

2021-03-01 15:09 UTC, apsevkin requested changes

2021-03-01 15:09 UTC, apsevkin commented on src/services/twilio.service.ts
> +      return await this.client.messages.create({
remove unnecessary await; add new params to function for a message body

2021-03-01 15:09 UTC, apsevkin commented on src/services/twilio.service.ts
> +      throw new HttpException(
handle http exception in the users controller

2021-03-01 15:09 UTC, apsevkin commented on src/users/users.service.ts
> +    const listPhonesCrossContacts = rawListCrossContacts.map(
remove it

2021-03-01 15:09 UTC, apsevkin commented on src/users/users.service.ts
> +    const listPhonesNotDuniapayContacts = rawListContactsPhone.filter(
use rawListContacts instead

2021-03-03 14:57 UTC, liubaterehova commented on src/users/users.controller.ts
> +  @Post('/current/notDuniapayUsers')
is it @Get method?

2021-03-03 16:17 UTC, liubaterehova requested changes

2021-03-03 16:17 UTC, liubaterehova commented on src/users/users.service.ts
> +        return rawListCrossContacts.findIndex(
so filter with findsIndex if find element with position '0' will return false. It's not correct behavior.

you need to compare with '-1'

2021-03-03 16:17 UTC, liubaterehova commented on src/users/users.service.ts
> +        return rawListCrossContacts.findIndex(
I'd like you to introduce another method/ It's more quick cause when we cause findIndex we need to compare all elements from the array every time. So it's more efficient to use Set.
it will be like 
`const contacts = new Set([rawListCrossContacts])`
and inside filter to check: `contacts.has(phoneNumber)`

2021-03-05 09:25 UTC, liubaterehova approved these changes

2021-03-05 09:25 UTC, merged