fix: when create user add additional keys
duniapay/backendtools pull request #26
Opened 2021-03-09 13:37 UTC by liubaterehova

2021-03-10 09:34 UTC, apsevkin approved these changes

2021-03-10 09:35 UTC, apsevkin requested changes

2021-03-10 09:35 UTC, apsevkin commented on src/auth/auth.service.ts
> +        birthDate: new Date(),
why do we set birthDay as a current date?

2021-03-10 09:35 UTC, apsevkin commented on src/auth/auth.service.ts
> +        birthDate: new Date(),
Maybe it would be better to set it as an empty string or null?

2021-03-11 08:58 UTC, apsevkin requested changes

2021-03-11 08:58 UTC, apsevkin commented on src/auth/dto/account.dto.ts
> +  public birthDate: Date;
I guess here should be union type Date | null

2021-03-11 11:26 UTC, liubaterehova commented on src/auth/dto/account.dto.ts
> +  public birthDate: Date;
It's not necessary to add null, cause any object can be null

2021-03-12 13:49 UTC, apsevkin approved these changes

2021-03-12 13:49 UTC, merged